---
collections:
  - name: community.general
  - name: ansible.posix
  - name: community.docker

roles:
  - name: docker_common_setup
    src: git+https://github.com/InvalidIdentifier/ansible-role-docker-common-setup.git
    version: main
    scm: git
